# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2022-07-22T15:05:59+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class Valid(BaseModel):
    response: Optional[str] = None
